### ISSUE TITLE
hidetatz/kubecolor is deprecated, it's now kubecolor/kubecolor

### ISSUE THREAD

**Issue by wmcnamee-coreweave** [dex4er/asdf-kubecolor#2]
hidetatz/kubecolor is deprecated, it's now kubecolor/kubecolor

**Comment by dex4er** [comment]
Fixed in [1eb8559](https://github.com/dex4er/asdf-kubecolor/commit/1eb85590d4e9ceab02d5a26c15b82cc8a0554a1d) Thanks a lot for your support!

**Comment by wmcnamee-coreweave** [comment]
🎉
